export const ADD_PRODUCT_IN_CART = "ADD_PRODUCT_IN_CART";
export const GET_PRODUCT_CART = "GET_PRODUCT_CART";
export const INCRIMENT_COUNT_CART = "INCRIMENT_COUNT_CART";
export const DECREMENT_COUNT_CART = "DECREMENT_COUNT_CART";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const CART_COUNT_PRODUCT = "CART_COUNT_PRODUCT";
export const SET_IS_FAVORITE_CART_PRODUCT = "SET_IS_FAVORITE_CART_PRODUCT";
export const FIND_AND_SET_IS_FAVORIT_IN_CART =
  "FIND_AND_SET_IS_FAVORIT_IN_CART";
export const EMPTY_SHOPPING_CART = "EMPTY_SHOPPING_CART";
